apiVersion: v1
kind: Service
metadata:
  name: java-demo
  namespace: default
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: java-demo
  selector:
    app: java-demo
  type: LoadBalancer
